{
 "title": "vSphere",
 "time": { "from": "now-24h", "to": "now" },
 "templating": {
  "list": [
   { "name": "cluster", "label": "vSphere Cluster", "query": "label_values(cluster)" }
  ]
 },
 "panels": [
  {
   "title": "Resources",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vsphere_cluster_cpu_usage{cluster=\"$cluster\"}/vsphere_cluster_cpu_effective{cluster=\"$cluster\"}*100",
     "legendFormat": "CPU"
    },
    {
     "expr": "vsphere_cluster_mem_usage{cluster=\"$cluster\"}/vsphere_cluster_mem_effective{cluster=\"$cluster\"}*100",
     "legendFormat": "Memory"
    }
   ]
  },
  {
   "title": "Cluster Activity",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "vsphere_cluster_vmop_numVMotion{cluster=\"$cluster\"}",
     "legendFormat": "vMotion vm"
    },
    {
     "expr": "vsphere_cluster_vmop_numDestroy{cluster=\"$cluster\"}",
     "legendFormat": "Delete vm"
    },
    {
     "expr": "vsphere_cluster_vmop_numPoweron{cluster=\"$cluster\"}",
     "legendFormat": "Power On vm"
    },
    {
     "expr": "vsphere_cluster_vmop_numPoweroff{cluster=\"$cluster\"}",
     "legendFormat": "Power Off vm"
    }
   ]
  },
  {
   "title": "Cluster CPU",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "hertz" }
   ],
   "targets": [
    {
     "expr": "vsphere_cluster_cpu_effective{cluster=\"$cluster\"}*1000000",
     "legendFormat": "Effective Total"
    },
    {
     "expr": "vsphere_cluster_cpu_usage{cluster=\"$cluster\"}*1000000",
     "legendFormat": "Usage"
    },
    {
     "expr": "vsphere_cluster_cpu_demand{cluster=\"$cluster\"}*1000000",
     "legendFormat": "Demand"
    },
    {
     "expr": "vsphere_cluster_cpu_total{cluster=\"$cluster\"}*1000000",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Cluster Memory",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 9 },
   "yaxes": [
    { "format": "decgbytes" }
   ],
   "targets": [
    {
     "expr": "vsphere_cluster_mem_effective{cluster=\"$cluster\"}",
     "legendFormat": "Effective Total"
    },
    {
     "expr": "vsphere_cluster_mem_usage{cluster=\"$cluster\"}",
     "legendFormat": "Usage"
    },
    {
     "expr": "vsphere_cluster_mem_ballooned{cluster=\"$cluster\"}",
     "legendFormat": "Ballooned"
    },
    {
     "expr": "vsphere_cluster_mem_swapped{cluster=\"$cluster\"}",
     "legendFormat": "Swapped"
    },
    {
     "expr": "vsphere_cluster_mem_total{cluster=\"$cluster\"}",
     "legendFormat": "Total"
    }
   ]
  },
  {
   "title": "Hypervisors CPU",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 18 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vsphere_host_cpu_pusage{cluster=\"$cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  },
  {
   "title": "Hypervisors Memory",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 26 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "vsphere_host_mem_pusage{cluster=\"$cluster\"}",
     "legendFormat": "{{host}}"
    }
   ]
  }
 ]
}